# Generated by Django 5.2.13 on 2026-04-07 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("circles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_circle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="circles.circle",
            ),
        ),
    ]
