# Generated by Django 5.2.13 on 2026-04-07 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circles", "0002_circle_circles_cir_slug_7b395a_idx_and_more"),
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["circle", "published"], name="events_even_circle__dadc7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["start_datetime"], name="events_even_start_d_b72861_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventsignup",
            index=models.Index(
                fields=["event", "status"], name="events_sign_event_i_66d2f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventsignup",
            index=models.Index(fields=["user"], name="events_sign_user_id_1c0c6a_idx"),
        ),
    ]
