# Generated by Django 5.2.13 on 2026-04-07 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circles", "0003_circle_address"),
        ("events", "0002_event_events_even_circle__dadc7e_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="visibility",
            field=models.CharField(
                choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                default="PRIVATE",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["visibility"], name="events_even_visibil_6abc2e_idx"
            ),
        ),
    ]
