# Generated by Django 5.2.13 on 2026-04-07 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="circle",
            index=models.Index(fields=["slug"], name="circles_cir_slug_7b395a_idx"),
        ),
        migrations.AddIndex(
            model_name="circle",
            index=models.Index(
                fields=["created_at"], name="circles_cir_created_ace838_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="circleinvite",
            index=models.Index(fields=["token"], name="circles_inv_token_67725c_idx"),
        ),
        migrations.AddIndex(
            model_name="circleinvite",
            index=models.Index(
                fields=["circle", "is_active"], name="circles_inv_circle__18e11b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="circlemembership",
            index=models.Index(
                fields=["circle", "active"], name="circles_mem_circle__2b439e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="circlemembership",
            index=models.Index(
                fields=["user", "active"], name="circles_mem_user_id_2ed14f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="circlemembership",
            index=models.Index(fields=["role"], name="circles_mem_role_155603_idx"),
        ),
    ]
