# Generated by Django 5.2.13 on 2026-04-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circles", "0002_circle_circles_cir_slug_7b395a_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="circle",
            name="address",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
